### ISSUE TITLE
`nvidia-cusolver-cu11` needs an additional override

### ISSUE THREAD

**Issue by dschrempf** [TyberiusPrime/uv2nix_hammer_overrides#6]
```
  nvidia-cusolver-cu11 = prev.nvidia-cusolver-cu11.overrideAttrs (old: {
    buildInputs = (old.buildInputs or [ ]) ++ [
      pkgs.cudaPackages_11.libcublas
    ];
  });
```

**Comment by TyberiusPrime** [comment]
I removed a bunch of nvidia overrides because we got a new byte-code-collision-but-identical-file detector in uv2nix (pyproject.nix) recently. 
They'll rerun eventually. 

I prioritized nvidia-cusolver-cu11, so that should be included now.

But keep in mind, cuda 11 is going away (see https://nixos.org/manual/nixos/unstable/release-notes#sec-release-24.11 ).

**Comment by dschrempf** [comment]
Thanks! Part of the problem was also that package version constrains forced us to use an older CUDA version. We have fixed this droping some packages, so we can use CUDA 12. For CUDA 12 all overlays are working, thanks a ton!
